#!/usr/local/node/bin/node

const { info, error } = require("../tools/colors");
const fs = require("fs");
const execSync = require("child_process").execSync;
const yaml = require("js-yaml");


/**
 *  @readme
 *      GitHookProduct: 自动化部署项目的自动化部署处理方案, 自身部署自身
 *          git_hooks_env: 给git-hooks的环境变量    
 *          hooks_dirname: 项目地址
 *          deploy_pathname: 需要执行的其他配置
 *          branchs: 需要部署的分支, 暂时不处理, 默认全部是master
 *  
 * 
 *      PostReceive: hook: post-receive 
 * 
 */

class GitHookProject {

    constructor (branchs){

        this.hooks_dirname = "/home/git/product/git-hooks";
        
        this.git_hooks_env = "\
            export PATH=/usr/local/node/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin \
            && unset GIT_DIR \
            && bash -c";

        this.deploy_pathname = "deploy.yaml";

        this.branchs = branchs;

    }

    run (){

        info("[info] 进入目录 %s", this.hooks_dirname);
        process.chdir(this.hooks_dirname);

        info("[info] 拉取更新");
        console.log(execSync(`${this.git_hooks_env} 'git pull'`).toString());

        const deploy_pathname = this.deploy_pathname;

        try {

            info("[info] 检查部署文件: %s 是否存在 ...", deploy_pathname);
            fs.accessSync(deploy_pathname);
            const f = fs.readFileSync(deploy_pathname);
            const task = yaml.safeLoad(f);
            info("[info] %s 存在 ...", deploy_pathname);

            if (task.run.length){
                for (let cmd of task.run){
                    info("[info] 执行命令: %s", cmd);
                    console.log(execSync(`${this.git_hooks_env} '${cmd}'`).toString());
                }
            }

            info("[info] success ...");

        } catch (err){
            error("[warning] %s 不存在, end ...", deploy_pathname);
        }
    }

}


class DeployProject {

    constructor (){

    }

    run (){
        console.log("项目...");

    }

}

class PostReceive {

    constructor (branchs){
        this.warehourse = null;
        this.branchs = branchs;
    }

    // 获取仓库名称
    __getWarehourseName (){


        console.log(process.cwd(), 222);
        

        let aPath = __filename.split("/");
        let index = aPath.findIndex( v => v === "hooks" );
        this.warehourse = aPath[index - 1];

    }

    run (){

        this.__getWarehourseName();
        info("[info] push仓库名: %s, 需要更新的分支: %s", this.warehourse, this.branchs.join(" , "));

        if (this.warehourse === "git-hooks") return new GitHookProject(this.branchs).run();

        new DeployProject().run();

    }

}

{
    if ( !module.parents ){

        (async () => {
            
            // 获取push的分支, 可以一次push多个分支
            process.stdin.setEncoding('utf8');
            const branchs = await new Promise(resolve => {
                const chunks = [];
                process.stdin.on('readable', () => {
                    const chunk = process.stdin.read();
                    if (chunk !== null) {
                        chunks.push(chunk);
                    }
                });
    
                process.stdin.on('end', () => {
                    const arr = chunks.join("").trim().split(" ");
                    const branchs = arr.splice(2);
                    resolve(branchs);
                });
            });

            // 处理 post-receive
            try {
                new PostReceive(branchs).run();
            } catch (err){
                error("[error] 发生了错误", err.toString());
            }
            
        })();
    }
}



