#!/usr/local/node/bin/node

const { info } = require("../tools/colors");

class PostReceive {

    constructor (branchs){
        this.warehourse = null;
        this.branchs = branchs;
    }

    __getWarehourseName (){
        let aPath = __filename.split("/");
        let index = aPath.findIndex( v => v === "hooks" );
        this.warehourse = aPath[index - 1];
    }

    exec (){
        this.__getWarehourseName();
        info("[info] push仓库名: %s, 需要更新的分支: %s", this.warehourse, this.branchs.join(" , "));
    }

}

{
    if ( !module.parents ){

        (async () => {

            // 获取push的分支
            // 可以一次push多个分支, 这里只处理了第一个
            process.stdin.setEncoding('utf8');
            const branchs = await new Promise(resolve => {
                const chunks = [];
                process.stdin.on('readable', () => {
                    const chunk = process.stdin.read();
                    if (chunk !== null) {
                        chunks.push(chunk);
                    }
                });
    
                process.stdin.on('end', () => {
                    const arr = chunks.join("").trim().split(" ");
                    const branchs = arr.splice(2);
                    resolve(branchs);
                });
            });

            const oPostReceive = new PostReceive(branchs);
            oPostReceive.exec();

        })();
    }
}



